version: '2'
services:
  web:
    build: .
    command: npm run dev
    networks:
      - mern-stack-net
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - '3000:5000'
    depends_on:
      - db
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - ACCESS_KEY_ID=${ACCESS_KEY_ID}
      - SECRET_ACCESS_KEY=${SECRET_ACCESS_KEY}
      - DB_NAME=${DB_NAME}
  db:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - mern-stack-net
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
  mongo-express:
    image: mongo-express
    depends_on:
      - db
    ports:
      - 8080:8081
    networks:
      - mern-stack-net
    volumes:
      - mongo-data:/data/db
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${DB_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${DB_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=db

networks:
  mern-stack-net:
    driver: bridge

volumes:
  mongo-data:
    driver: local
