# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI / CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  id-token: write
  contents: read

jobs:
  test:
    name: Test backend project
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Installing dependencies
        uses: ./.github/actions/install_deps
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run the tests and generate coverage report
        run: yarn exec concurrently yarn:test:ci yarn:lint yarn:check-types

  release:
    name: Run semantic release
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Installing dependencies
        uses: ./.github/actions/install_deps
        with:
          node-version: ${{ matrix.node-version }}
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.DEPLOYMENT_ROLE }}
          role-session-name: DeployBackendSession
          role-duration-seconds: 900
          aws-region: us-east-1
      - name: Install serverless
        run: npm i -g serverless@2.72.2
      - name: Deploy to AWS Lambda
        run: serverless deploy --verbose --dbuser ${DB_USERNAME} --password ${DB_PASSWORD} --stage prod
        env:
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      - name: Release new version
        run: yarn semantic-release
        env:
          GH_TOKEN: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
          HUSKY: 0
